name: CI Building & Testing Image

on:
  push:
    branches: [ "main" ]
    # tags: type=sha,format=long
  pull_request:
    branches: [ "main" ]
    # tags: type=sha,format=long
  workflow_dispatch:


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build-and-push-image:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: 
          ${{ github.sha }}
        #   type=sha,format=long
        #   type=raw,value=latest
        flavor: latest=true

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Test and upload test output as artifact
      run: |
        mkdir -p ${{ github.workspace }}/output
        mkdir -p ${{ github.workspace }}/examples                         #-u $(id -u):$(id -g) 
        docker run --rm -v ${{ github.workspace }}/output:/arg-fuzz/output ${{ env.REGISTRY }}/${{  env.IMAGE_NAME  }}:latest
        sudo chmod 744 -R ${{ github.workspace }}/output
    - uses: actions/upload-artifact@v4
      with:
        name: test-output
        path: ${{ github.workspace }}/output
        compression-level: 6 #default
